### ISSUE TITLE
Skip workflow if not dependabot

### ISSUE THREAD

**Issue by jayvdb** [jo-sm/at-dependabot-merge#1]
I am using a slightly modified job that includes the following so that this action doesnt run if the PR is created by a different user.

```
if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' && github.actor == 'dependabot[bot]' }}
```

I realise that this github action also does the same filtering inside the action, however some users may prefer that the action doesnt run at all for the wrong user, if only because workflows can be filtered out in the Actions tab of PRs to exclude skipped workflows.

It might be useful to include this in the README.

**Comment by jo-sm** [comment]
Hey @jayvdb, thanks for the issue and I think that makes sense, and it's not very clear from the official docs how to do this too. I'll update the readme with some info on that!
